In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
# NumPy's main datatype is ndarray (n-dim array)
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)


numpy.ndarray

In [4]:
a2 = np.array([[1, 2, 3],
             [4, 5, 6.5]])
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[10,11,12],
               [13,14,15],
               [16,17,18]]])

In [5]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [6]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a3)

numpy.ndarray

In [15]:
# Create a DataFram from NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.5

## 2. Create Arrays

In [17]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [18]:
ones = np.ones((2,3))

In [19]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
ones.dtype

dtype('float64')

In [22]:
type(ones)

numpy.ndarray

In [23]:
zeros = np.zeros((2,3))

In [24]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
range_array = np.arange(0,10,2)

In [26]:
range_array

array([0, 2, 4, 6, 8])

In [27]:
random_array = np.random.randint(0, 10, size=(3,5))
random_array

array([[1, 8, 3, 1, 4],
       [3, 1, 8, 8, 9],
       [1, 3, 9, 6, 2]])

In [28]:
random_array.size

15

In [29]:
random_array.shape

(3, 5)

In [34]:
# Pseudo-random numbers
np.random.seed(seed=0)

random_4 = np.random.randint(10,size=(5,3))
random_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

## Viewing Arrays and Matrices

In [35]:
np.unique(random_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [37]:
a3[1:,1:,1:]

array([[[14, 15],
        [17, 18]]])

In [40]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [41]:
# get the first four numbers of the inner most array
a4[:,:,:,:4]

array([[[[6, 7, 7, 8],
         [5, 9, 8, 9],
         [3, 0, 3, 5],
         [2, 3, 8, 1]],

        [[3, 3, 7, 0],
         [9, 9, 0, 4],
         [3, 2, 7, 2],
         [0, 4, 5, 5]],

        [[8, 4, 1, 4],
         [8, 1, 1, 7],
         [9, 3, 6, 7],
         [0, 3, 5, 9]]],


       [[[4, 6, 4, 4],
         [4, 4, 8, 4],
         [7, 5, 5, 0],
         [5, 9, 3, 0]],

        [[0, 1, 2, 4],
         [0, 3, 2, 0],
         [5, 9, 0, 2],
         [2, 9, 2, 3]],

        [[2, 3, 4, 1],
         [9, 1, 4, 6],
         [2, 3, 0, 0],
         [0, 6, 3, 3]]]])

## 4. Manipulating & comparing arrays

### Arithmetic

In [42]:
a1

array([1, 2, 3])

In [43]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [44]:
ones = np.ones(3)

In [45]:
ones

array([1., 1., 1.])

In [46]:
a1+ones

array([2., 3., 4.])

In [47]:
a1 - ones

array([0., 1., 2.])

In [48]:
a1 * ones

array([1., 2., 3.])

In [49]:
a1 * a2

array([[ 1. ,  4. ,  9. ],
       [ 4. , 10. , 19.5]])

In [50]:
from matplotlib.image import imread

panda = imread(fname = "IMG_6862.jpg")
panda

array([[[118, 105,  71],
        [114, 101,  69],
        [124, 111,  79],
        ...,
        [ 51,  54,  23],
        [ 64,  69,  28],
        [ 71,  77,  33]],

       [[112,  99,  67],
        [117, 104,  70],
        [130, 118,  80],
        ...,
        [ 61,  67,  29],
        [ 62,  70,  29],
        [ 52,  58,  22]],

       [[117, 104,  70],
        [129, 116,  81],
        [108,  94,  65],
        ...,
        [ 54,  55,  21],
        [ 62,  62,  24],
        [ 53,  54,  22]],

       ...,

       [[ 44,  51,  70],
        [ 71,  87, 120],
        [ 55,  63,  86],
        ...,
        [ 59,  64, 106],
        [ 39,  43,  78],
        [ 62,  75, 119]],

       [[ 47,  59,  81],
        [ 55,  62,  91],
        [ 77,  87, 122],
        ...,
        [ 43,  49,  81],
        [ 43,  51,  87],
        [ 43,  56,  91]],

       [[ 77,  92, 123],
        [ 68,  82, 111],
        [ 45,  58,  77],
        ...,
        [ 53,  62, 101],
        [ 56,  69, 113],
        [ 35,  41,  73]]

In [51]:
panda.size, panda.shape, panda.ndim

(64008000, (5334, 4000, 3), 3)